peso=float(input('digite seu peso em kg:'))
altura=float(input('digite sua altura em metros:'))
imc=(peso/(altura**2))
print('seu imc é de: {}'.format(imc))
print('O IMC é usado para saber se a pessoa está, abaixo do peso, com o peso normal, sobrepeso ou esta com obesidade, você tera uma base atravez da tabela a seguir:')
print('Abaixo do peso: IMC abaixo 18,5')
print('peso normal: IMC entre 18,5 e 24,9')
print('sobrepeso: IMC entre 25 e 29,9')
print('obsidade:IMC 30 ou superior')
